routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

# Marketplace

use Illuminate\Support\Facades\Route;


Route::get('market', 'MarketController@listContacts');
// Route::get('market/contact/add', 'MarketController@showAddContactForm');
// Route::post('market/contact/add', 'MarketController@saveContact');
Route::get('contact/view/{contactID}', 'MarketController@viewContact');
Route::get('contacts/search', 'MarketController@searchContact');

# Services
Route::get('/', 'CookbookController@index');
Route::get('/landing', 'ServiceController@showServices');

Route::get('services', 'ServiceController@showServices');
Route::get('enquiry/{type}', 'ServiceController@loadEnquiry');
Route::post('enquiry/save', 'ServiceController@saveEnquiry');

Route::get('disclaimer', 'ServiceController@showDisclaimer');

# Basket
Route::get('basket', 'ServiceController@basket');
Route::get('remove/from/cart/{productID}', 'ServiceController@removeFromCart');

Route::post('request/connect', 'MarketController@connect');

# Admin panel
Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {

    Route::get('home', 'Admin\HomeController@index');

    Route::get('contacts', 'Admin\ContactController@listContacts');
    Route::get('contact/edit/{contactID}', 'Admin\ContactController@editContact');
    Route::post('contact/save', 'Admin\ContactController@updateContact');
    Route::get('contact/view/{contactID}', 'Admin\ContactController@viewContact');
    Route::get('contacts/map', 'Admin\ContactController@renderMap');

    Route::get('contact/add', 'Admin\ContactController@showAddContactForm');
    Route::post('contact/add', 'Admin\ContactController@saveContact');

    Route::get('contact/requests', 'Admin\ContactController@showRequests');

    Route::get('contact/search', 'Admin\ContactController@searchContacts');

    # Service enquiries dashboard
    Route::get('enquiries', 'Admin\EnquiryController@listEnquiries');
    Route::get('enquiry/view/{enquiryID}', 'Admin\EnquiryController@viewEnquiry');
    Route::get('enquiries/export/excel', 'Admin\EnquiryController@exportExcel');

    # User management
    Route::get('users', 'Admin\UserManager@listUsers');


    Route::get('logout', 'UsersController@logout');
});

Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');

# Utility routes
Route::get('/import', 'ImportController');


#### NEW SYSTEM ###
Route::group(['middleware' => 'auth'], function () {
    Route::get('dashboard', 'DashboardController')->middleware('admin');
    Route::get('ads/{id}/delete', 'AdsController@destroy')->middleware('admin');
    Route::resource('ads', 'AdsController')->middleware('admin');

    Route::get('orders/{orderID}/delete', 'OrdersController@destroy')->middleware('admin');
    Route::post('orders/{orderID}/note', 'OrdersController@saveNote')->middleware('admin');
    Route::get('orders/{orderID}/pdf', 'OrdersController@makePDF')->middleware('admin');
    Route::post('orders/search', 'OrdersController@search')->name('orders.search')->middleware('admin');
    Route::resource('orders', 'OrdersController')->middleware('admin');

    Route::get('users/{id}/delete', 'UsersController@destroy')->middleware('admin');
    Route::resource('users', 'UsersController')->middleware('admin');
    Route::get('service-providers', 'UsersController@listSPs')->middleware('admin');

    Route::get('logout', 'UsersController@logout');

    Route::get('payments', 'PaymentController@list')->middleware('admin');

    # Bulk SMS
    Route::get('sms', 'BulkSMSController@index')->middleware('admin');
    Route::post('sms', 'BulkSMSController@sendMessages')->middleware('admin');
});

Route::get('onboard', 'ServiceController@showSpOnboardingPage');
Route::post('onboard', 'ServiceController@startOnboard');

Route::get('stkpush', 'STKPush@test');

Route::get('you-can-now-login', 'UsersController@youCanLogIn');

// Profile Settings
Route::prefix('profile')->middleware('auth')->group( function ()
    {
        Route::get('edit', 'ProfileController@edit');
        Route::put('update', 'ProfileController@update');
    }
);

# Cookbook
Route::get('cookbook', 'CookbookController@index');
Route::get('locale/{locale}', 'CookbookController@switchLocale');
Route::get('cookbook/my-purchases', 'CookbookController@myPurchases')->middleware('auth');
Route::get('/cookbook/my-purchases/{id}', 'CookbookController@showPurchase');
Route::get('cookbook/{locale}', 'CookbookController@index');
Route::get('cookbook/veges/{id}', 'CookbookController@vegesOrder')->name('vegesOrder');
Route::post('cookbook/cart/veges/add/{id}', 'CookbookController@addVegiesOrderToCart')->name('addVegiesOrderToCart');
Route::get('cookbook/display/{id}', 'CookbookController@display'); #->middleware('auth');
Route::get('cookbook/purchase/{id}', 'CookbookController@purchase')->middleware('auth');
Route::get('cookbook/dl/{productKey}/{purchaseToken}', 'CookbookController@activatePurchase')->middleware('auth');
Route::get('cookbook/download/{purchaseID}/{productID}', 'CookbookController@download')->middleware('auth');
Route::get('cookbook/cart/add/{id}', 'CookbookController@addToCart');

Route::get('cookbook/cart/display', 'CookbookController@displayCart');
Route::get('cookbook/cart/checkout', 'CookbookController@checkout')->name('checkout')->middleware('auth');
Route::get('cookbook/cart/checkout/{payment}', 'CookbookController@initiateStkPushPayment')->middleware('auth'); //mpesa till
Route::get('cookbook/cart/checkPaymentStatus/{payment}', 'CookbookController@checkPaymentStatus');

Route::post('cookbook/cart/checkout/setCustomAddress', 'CookbookController@setCustomAddress')->middleware('auth');
Route::get('cookbook/cart/remove/{raw}', 'CookbookController@removeFromCart');
Route::get('cookbook/cart/veges/display', 'CookbookController@displayVegesCart');
// Route::get('cookbook/cart/veges/remove/{raw}', 'CookbookController@removeVegeFromCart');
Route::get('cookbook/cart/mpesa/finish/{payment}/{reference}', 'CookbookController@mpesaTillSuccess')->middleware('auth');

# Pesapal 
Route::get('payment/received', ['as' => 'pesapalSuccess', 'uses' => 'PaymentController@pesapalReceived']);
Route::get('webhooks/pesapal/confirmation', ['as' => 'pesapalConfirmation', 'uses' => 'PaymentController@pesapalConfirmation']);

Route::get('pay/pesapal/confirmation', ['as' => 'handlePesapalCallback', 'uses' => 'CookbookController@handlePesapalCallback']);

# Paypal
Route::get('cookbook/paypal/success', 'CookbookController@paypalSuccess');


# Admin panel
Route::get('admin/cookbook/sales', 'CookbookController@showSales')->middleware(['auth', 'admin']);

# Submit recipe
Route::get('submit/recipe', 'CookbookController@showRecipeSubmitForm');
Route::post('submit/recipe', 'CookbookController@submitRecipe');


Route::get('preview/cookbook', 'UsersController@previewCookbook');

Route::post('order/veges', 'CookbookController@orderVeges');

resources/views/admin/dashboard.blade.php
@extends('layout.admin.master')

@section('title')
    Welcome to {{ config('app.name') }}!
@endsection

@section('page')
    <main class="main-content bgc-grey-100">
        <div id="mainContent">

            <div class="content">

                <div class="row">
                    <div class="col-md-4">
                        <div class="layers bd bgc-white p-20">
                            <div class="layer w-100 mB-10"><h6 class="lh-1">Registered Users</h6></div>
                            <div class="layer w-100">
                                <div class="peers ai-sb fxw-nw">
                                    <div class="peer">
                                        <h2>{{ $total['accounts'] }}</h2>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="layers bd bgc-white p-20">
                            <div class="layer w-100 mB-10"><h6 class="lh-1">Recipe Book Sales</h6></div>
                            <div class="layer w-100">
                                <div class="peers ai-sb fxw-nw">
                                    <div class="peer">
                                        <h2>Ksh {{ number_format($total['cookbook_sales']) }}</h2>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="layers bd bgc-white p-20">
                            <div class="layer w-100 mB-10"><h6 class="lh-1">Total Sales</h6></div>
                            <div class="layer w-100">
                                <div class="peers ai-sb fxw-nw">
                                    <div class="peer">
                                        <h2>Ksh {{ number_format($total['total_transacted']) }}</h2>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row mt-3">
                    <div class="col-md-3 mb-3">
                        <div class="layers bd bg-dark text-white p-20">
                            <div class="layer w-100 mB-10"><h6 class="lh-1">Total Service Providers</h6></div>
                            <div class="layer w-100">
                                <div class="peers ai-sb fxw-nw">
                                    <div class="peer">
                                        <h2>{{ $total['SPs'] }}</h2>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-3 mb-3">
                        <div class="layers bd bg-dark text-white p-20">
                            <div class="layer w-100 mB-10"><h6 class="lh-1">Total Customers</h6></div>
                            <div class="layer w-100">
                                <div class="peers ai-sb fxw-nw">
                                    <div class="peer">
                                        <h2>{{ $total['customers'] }}</h2>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-3 mb-3">
                        <div class="layers bd bg-dark text-white p-20">
                            <div class="layer w-100 mB-10"><h6 class="lh-1">Total Orders</h6></div>
                            <div class="layer w-100">
                                <div class="peers ai-sb fxw-nw">
                                    <div class="peer">
                                        <h2>{{ $total['orders']['total'] }}</h2>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-3 mb-3">
                        <div class="layers bd bg-dark text-white p-20">
                            <div class="layer w-100 mB-10"><h6 class="lh-1">Total Ads</h6></div>
                            <div class="layer w-100">
                                <div class="peers ai-sb fxw-nw">
                                    <div class="peer">
                                        <h2>{{ $total['ads'] }}</h2>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-3 mb-3">
                        <div class="layers bd bg-danger text-white p-20">
                            <div class="layer w-100 mB-10"><h6 class="lh-1">Pending Orders</h6></div>
                            <div class="layer w-100">
                                <div class="peers ai-sb fxw-nw">
                                    <div class="peer">
                                        <h2>{{ number_format($total['orders']['pending']) }}</h2>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3 mb-3">
                        <div class="layers bd bg-primary text-white p-20">
                            <div class="layer w-100 mB-10"><h6 class="lh-1">Progressing Orders</h6></div>
                            <div class="layer w-100">
                                <div class="peers ai-sb fxw-nw">
                                    <div class="peer">
                                        <h2>{{ number_format($total['orders']['progressing']) }}</h2>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3 mb-3">
                        <div class="layers bd bg-success text-white p-20">
                            <div class="layer w-100 mB-10"><h6 class="lh-1">Completed Orders</h6></div>
                            <div class="layer w-100">
                                <div class="peers ai-sb fxw-nw">
                                    <div class="peer">
                                        <h2>{{ number_format($total['orders']['completed']) }}</h2>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row mt-5">
                    <div class="col-md-12">
                        <div class="bgc-white bd bdrs-3 p-20 mB-20">
                            <h3>Here are 10 latest orders</h3>
                            <hr>
                            <table class="table table-bordered">
                                <thead>
                                <tr>
                                    <th scope="col" colspan="2">Product</th>
                                    <th scope="col">Customer</th>
                                    <th scope="col">Provider</th>
                                    <th scope="col">Price</th>
                                    <th scope="col">Location</th>
                                    <th scope="col" colspan="2">Status</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($orders as $order)
                                    @php
                                        if($order->status == 'PENDING'){
                                            $class = 'text-warning';
                                            $icon = 'clock-o';
                                        } else if($order->status == 'PROGRESSING'){
                                            $class = 'text-primary';
                                            $icon = 'refresh-circle fa-spin';
                                        } else if($order->status == 'COMPLETE'){
                                            $class = 'text-success';
                                            $icon = 'check-circle';
                                        } else if($order->status == 'CANCELLED'){
                                            $class = 'text-danger';
                                            $icon = 'times-circle';
                                        }
                                    @endphp
                                    <tr class="{{ $class }}">
                                        <td>
                                            <i class="fa fa-{{ $icon }}"></i>
                                        </td>
                                        <td>{{ $order->ad->name }}</td>
                                        <td>{{ @$order->customer->name }}</td>
                                        <td>{{ @$order->ad->publisher->name }}</td>
                                        <td>Ksh {{ number_format($order->ad->price) }}</td>
                                        <td>{{ @str_limit($order->customer->location['display_name'], 30) }}</td>
                                        <td>{{ $order->status }}</td>
                                        <td>
                                            {{ $order->expiry }}
                                            <a href="{{ route('orders.show', ['ad'=>$order->id]) }}"
                                               class="btn btn-outline-primary btn-sm pull-right">
                                                Details
                                            </a>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </main>

    <style>
        .text-warning {
            color: saddlebrown !important;
        }
    </style>
@endsection

resources/views/admin/home.blade.php
@extends('layout.admin.master')

@section('content')

<h3 class="text-primary mb-4">List of marketplace contacts</h3>
<hr>

<div class="row">
    <div class="col-lg-6  mb-4">
        <div class="card">
            <div class="card-block">
                <h5 class="card-title mb-4">Sales</h5>
                <canvas id="lineChart" style="height:250px"></canvas>
            </div>
        </div>
    </div>
    <div class="col-lg-6  mb-4">
        <div class="card">
            <div class="card-block">
                <h5 class="card-title mb-4">Customer Satisfaction</h5>
                <canvas id="doughnutChart" style="height:250px"></canvas>
            </div>
        </div>
    </div>
</div>

@endsection