routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

# Marketplace

use Illuminate\Support\Facades\Route;


Route::get('market', 'MarketController@listContacts');
// Route::get('market/contact/add', 'MarketController@showAddContactForm');
// Route::post('market/contact/add', 'MarketController@saveContact');
Route::get('contact/view/{contactID}', 'MarketController@viewContact');
Route::get('contacts/search', 'MarketController@searchContact');

# Services
Route::get('/', 'CookbookController@index');
Route::get('/landing', 'ServiceController@showServices');

Route::get('services', 'ServiceController@showServices');
Route::get('enquiry/{type}', 'ServiceController@loadEnquiry');
Route::post('enquiry/save', 'ServiceController@saveEnquiry');

Route::get('disclaimer', 'ServiceController@showDisclaimer');

# Basket
Route::get('basket', 'ServiceController@basket');
Route::get('remove/from/cart/{productID}', 'ServiceController@removeFromCart');

Route::post('request/connect', 'MarketController@connect');

# Admin panel
Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {

    Route::get('home', 'Admin\HomeController@index');

    Route::get('contacts', 'Admin\ContactController@listContacts');
    Route::get('contact/edit/{contactID}', 'Admin\ContactController@editContact');
    Route::post('contact/save', 'Admin\ContactController@updateContact');
    Route::get('contact/view/{contactID}', 'Admin\ContactController@viewContact');
    Route::get('contacts/map', 'Admin\ContactController@renderMap');

    Route::get('contact/add', 'Admin\ContactController@showAddContactForm');
    Route::post('contact/add', 'Admin\ContactController@saveContact');

    Route::get('contact/requests', 'Admin\ContactController@showRequests');

    Route::get('contact/search', 'Admin\ContactController@searchContacts');

    # Service enquiries dashboard
    Route::get('enquiries', 'Admin\EnquiryController@listEnquiries');
    Route::get('enquiry/view/{enquiryID}', 'Admin\EnquiryController@viewEnquiry');
    Route::get('enquiries/export/excel', 'Admin\EnquiryController@exportExcel');

    # User management
    Route::get('users', 'Admin\UserManager@listUsers');


    Route::get('logout', 'UsersController@logout');
});

Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');

# Utility routes
Route::get('/import', 'ImportController');


#### NEW SYSTEM ###
Route::group(['middleware' => 'auth'], function () {
    Route::get('dashboard', 'DashboardController')->middleware('admin');
    Route::get('ads/{id}/delete', 'AdsController@destroy')->middleware('admin');
    Route::resource('ads', 'AdsController')->middleware('admin');

    Route::get('orders/{orderID}/delete', 'OrdersController@destroy')->middleware('admin');
    Route::post('orders/{orderID}/note', 'OrdersController@saveNote')->middleware('admin');
    Route::get('orders/{orderID}/pdf', 'OrdersController@makePDF')->middleware('admin');
    Route::post('orders/search', 'OrdersController@search')->name('orders.search')->middleware('admin');
    Route::resource('orders', 'OrdersController')->middleware('admin');

    Route::get('users/{id}/delete', 'UsersController@destroy')->middleware('admin');
    Route::resource('users', 'UsersController')->middleware('admin');
    Route::get('service-providers', 'UsersController@listSPs')->middleware('admin');

    Route::get('logout', 'UsersController@logout');

    Route::get('payments', 'PaymentController@list')->middleware('admin');

    # Bulk SMS
    Route::get('sms', 'BulkSMSController@index')->middleware('admin');
    Route::post('sms', 'BulkSMSController@sendMessages')->middleware('admin');
});

Route::get('onboard', 'ServiceController@showSpOnboardingPage');
Route::post('onboard', 'ServiceController@startOnboard');

Route::get('stkpush', 'STKPush@test');

Route::get('you-can-now-login', 'UsersController@youCanLogIn');

// Profile Settings
Route::prefix('profile')->middleware('auth')->group( function ()
    {
        Route::get('edit', 'ProfileController@edit');
        Route::put('update', 'ProfileController@update');
    }
);

# Cookbook
Route::get('cookbook', 'CookbookController@index');
Route::get('locale/{locale}', 'CookbookController@switchLocale');
Route::get('cookbook/my-purchases', 'CookbookController@myPurchases')->middleware('auth');
Route::get('/cookbook/my-purchases/{id}', 'CookbookController@showPurchase');
Route::get('cookbook/{locale}', 'CookbookController@index');
Route::get('cookbook/veges/{id}', 'CookbookController@vegesOrder')->name('vegesOrder');
Route::post('cookbook/cart/veges/add/{id}', 'CookbookController@addVegiesOrderToCart')->name('addVegiesOrderToCart');
Route::get('cookbook/display/{id}', 'CookbookController@display'); #->middleware('auth');
Route::get('cookbook/purchase/{id}', 'CookbookController@purchase')->middleware('auth');
Route::get('cookbook/dl/{productKey}/{purchaseToken}', 'CookbookController@activatePurchase')->middleware('auth');
Route::get('cookbook/download/{purchaseID}/{productID}', 'CookbookController@download')->middleware('auth');
Route::get('cookbook/cart/add/{id}', 'CookbookController@addToCart');

Route::get('cookbook/cart/display', 'CookbookController@displayCart');
Route::get('cookbook/cart/checkout', 'CookbookController@checkout')->name('checkout')->middleware('auth');
Route::get('cookbook/cart/checkout/{payment}', 'CookbookController@initiateStkPushPayment')->middleware('auth'); //mpesa till
Route::get('cookbook/cart/checkPaymentStatus/{payment}', 'CookbookController@checkPaymentStatus');

Route::post('cookbook/cart/checkout/setCustomAddress', 'CookbookController@setCustomAddress')->middleware('auth');
Route::get('cookbook/cart/remove/{raw}', 'CookbookController@removeFromCart');
Route::get('cookbook/cart/veges/display', 'CookbookController@displayVegesCart');
// Route::get('cookbook/cart/veges/remove/{raw}', 'CookbookController@removeVegeFromCart');
Route::get('cookbook/cart/mpesa/finish/{payment}/{reference}', 'CookbookController@mpesaTillSuccess')->middleware('auth');

# Pesapal 
Route::get('payment/received', ['as' => 'pesapalSuccess', 'uses' => 'PaymentController@pesapalReceived']);
Route::get('webhooks/pesapal/confirmation', ['as' => 'pesapalConfirmation', 'uses' => 'PaymentController@pesapalConfirmation']);

Route::get('pay/pesapal/confirmation', ['as' => 'handlePesapalCallback', 'uses' => 'CookbookController@handlePesapalCallback']);

# Paypal
Route::get('cookbook/paypal/success', 'CookbookController@paypalSuccess');


# Admin panel
Route::get('admin/cookbook/sales', 'CookbookController@showSales')->middleware(['auth', 'admin']);

# Submit recipe
Route::get('submit/recipe', 'CookbookController@showRecipeSubmitForm');
Route::post('submit/recipe', 'CookbookController@submitRecipe');


Route::get('preview/cookbook', 'UsersController@previewCookbook');

Route::post('order/veges', 'CookbookController@orderVeges');

app/Models/Order.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Order extends Model
{

    use SoftDeletes;

    protected $table = 'orders';
    protected $guarded = ['id', 'created_at'];

    protected $casts = [
        'extra_data' => 'array',
        'delivery_location' => 'array',
    ];

    function customer()
    {
        return $this->belongsTo(User::class, 'customer_id', 'id');
    }

    function ad()
    {
        return $this->hasOne(Ad::class, 'id', 'ad_id');
    }

    function logs()
    {
        return $this->hasMany(ActivityLog::class, 'order_id', 'id');
    }
}

app/Models/ServiceOrder.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class ServiceOrder extends Model
{
	private $_type;

    protected $table = 'service_orders';

    protected $guarded = ['id', 'created_at'];

    protected $casts = [
        'tools_required'     => 'array',
        'logistics_required' => 'array',
        'vendor_required'    => 'array',
    ];

    function getTypeAttribute($value)
    {
    	$this->_type = $value;
    	return config('settings.formTypes')[$value];
    }

    function getCategoryAttribute($value)
    {
    	return config('settings.services.'.$this->_key($this->_type))[$value];
    }

    private function _key($type)
    {
    	if($type == 'FARM-MANAGEMENT') {
    		return 'farm';
    	}
    }

    function getCountyAttribute($value)
    {
    	return @config('settings.counties')[$value];
    }
}

app/Http/Controllers/API/OrderController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use App\Library\SMS;
use App\Mail\OrderAccepted;
use App\Mail\OrderCompleted;
use App\Mail\OrderProgressing;
use App\Mail\OrderReceived;
use App\Mail\OrderCancelled;
use App\Mail\OrderSent;
use App\Models\Ad;
use App\Models\Order;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Validator;

class OrderController extends Controller
{

    public function __construct()
    {
        $this->middleware('jwt.auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $orders = Order::with(['customer', 'ad.publisher', 'logs._publisher'])
            ->where('customer_id', auth()->id())
            ->orderBy('created_at', 'DESC')
            ->paginate(config('settings.page_size'));

        return response()->json($orders);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if (!request()->ad_id) {
            return response()->json(['error' => 'Please reference a valid ad ID']);
        }

        # Deduct 1 token from SP
        $sp = Ad::find(request()->ad_id)->publisher;

        # SP must have credits to receive orders
        if ($sp->credits <= 0) {
            return response()->json(['error' => 'This service provider cannot receive your order. Please try again leter']);
        }

        $order = request()->only(['ad_id', 'instructions']);
        $order['customer_id'] = auth()->id();
        $order['sp_id'] = Ad::with('publisher')->find(request()->ad_id)->publisher->id;
        $order['extra_data'] = request()->eventOptions;
        $order['delivery_location'] = request()->deliveryLocation;
        $order['status'] = 'PENDING';

        $order = Order::create($order);

        $order = Order::with(['customer', 'ad'])->find($order->id);

        # Notify publisher via email
        Mail::to($order->ad->publisher)->send(new OrderReceived($order));

        # Notify buyer via email
        Mail::to($order->customer)->send(new OrderSent($order));

        # Notify SP of new order
        $msisdn = SMS::formatMSISDN($order->ad->publisher->telephone);
        if ($msisdn) {
            $text = config('settings.sms.templates.sp_new_order');
            $text = str_replace('{CUSTOMER}', $order->customer->name, $text);
            $text = str_replace('{PRODUCT}', $order->ad->name, $text);
            $text = str_replace('{PRICE}', number_format($order->ad->price), $text);
            @SMS::send($msisdn, $text);
        }

        # Acknowledge to customer order received
        $msisdn = SMS::formatMSISDN($order->customer->telephone);
        if ($msisdn) {
            $text = config('settings.sms.templates.customer_order_received');
            $text = str_replace('{PRODUCT}', $order->ad->name, $text);
            $text = str_replace('{PRICE}', number_format($order->ad->price), $text);
            $text = str_replace('{BUSINESS}', $order->ad->publisher->business_name, $text);
            @SMS::send($msisdn, $text);
        }

        return response()->json(['status' => 'OK']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show()
    {
        $order = Order::with(['customer', 'ad.publisher', 'logs._publisher'])->find(request()->orderID);

        return response()->json($order);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        $validation = Validator::make($request->all(), [
            'orderID'      => 'required',
            'status'       => 'required',
            'instructions' => 'required'
        ], [
            'orderID.required' => 'Please attach the orderID'
        ]);

        if ($validation->fails()) {
            return response()->json(['error' => $validation->errors()->first()]);
        }

        Order::find($request->orderID)->update([
            'status'       => $request->status,
            'instructions' => $request->instructions,
        ]);

        $order = Order::with(['customer', 'ad.publisher', 'logs._publisher'])->find($request->orderID);

        if ($request->status == 'PROGRESSING') {
            Mail::to($order->customer->email)->send(new OrderProgressing($order));
        }

        return response()->json($order);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    function getSPOrders()
    {
        $orders = Order::with(['ad.publisher', 'customer'])
            ->where('sp_id', request()->spID)
            ->orderBy('created_at', 'DESC')
            ->paginate();

        return response()->json($orders);
    }

    function cancelOrder()
    {
        if (!request()->id || !request()->reason) {
            return response()->json(['error' => 'Please attach the required fields']);
        }

        $order = Order::with(['customer', 'ad.publisher', 'logs._publisher'])->find(request()->id);

        if (!$order) {
            return response()->json(['error' => 'This order does not exist']);
        }

        $order->update([
            'status'              => 'CANCELLED',
            'cancellation_reason' => request()->reason
        ]);

        $order = Order::with(['customer', 'ad.publisher', 'logs._publisher'])->find(request()->id);

        # Notify customer
        Mail::to($order->customer->email)->send(new OrderCancelled($order));

        # Notify customer of order cancellation via SMS
        $msisdn = SMS::formatMSISDN($order->customer->telephone);
        if ($msisdn) {
            $text = config('settings.sms.templates.customer_order_cancelled');
            $text = str_replace('{PRODUCT}', $order->ad->name, $text);
            $text = str_replace('{PRICE}', number_format($order->ad->price), $text);
            $text = str_replace('{BUSINESS}', $order->ad->publisher->business_name, $text);
            @SMS::send($msisdn, $text);
        }

        return response()->json($order);
    }

    function acceptOrder()
    {
        if (!request()->id) {
            return response()->json(['error' => 'Please attach the required fields']);
        }

        $order = Order::with(['customer', 'ad.publisher', 'logs._publisher'])->find(request()->id);

        if (!$order) {
            return response()->json(['error' => 'This order does not exist']);
        }

        $order->update([
            'status' => 'PROGRESSING'
        ]);

        $order = Order::with(['customer', 'ad.publisher', 'logs._publisher'])->find(request()->id);

        # Notify customer
        Mail::to($order->customer)->send(new OrderAccepted($order));

        # Notify publisher of order via SMS
        $msisdn = SMS::formatMSISDN($order->customer->telephone);
        if ($msisdn) {
//            @SMS::send($msisdn, 'Hello world from here');
        }

        return response()->json($order);
    }

    function completeOrder()
    {
        if (!request()->id) {
            return response()->json(['error' => 'Please attach the required fields']);
        }

        $order = Order::with(['customer', 'ad.publisher', 'logs._publisher'])->find(request()->id);

        if (!$order) {
            return response()->json(['error' => 'This order does not exist']);
        }

        $sp = $order->ad->publisher;

//        dd($sp);

        $sp->update(['credits' => ($sp->credits - config('settings.credit_values'))]);


        $order->update([
            'status' => 'COMPLETE'
        ]);

        $order = Order::with(['customer', 'ad.publisher', 'logs._publisher'])->find(request()->id);

        Mail::to($order->customer)->send(new OrderCompleted($order));

        # Notify customer of order completion via SMS
        $msisdn = SMS::formatMSISDN($order->customer->telephone);
        if ($msisdn) {
//            @SMS::send($msisdn, 'Hello world from here');
        }

        return response()->json($order);
    }
}

resources/views/orders/show.blade.php
@extends('layout.admin.master')

@section('title')
    Order #{{ $order->id }}
@endsection

@section('page')
    <main class="main-content bgc-grey-100">
        <div id="mainContent">

            <div class="content">

                <div class="row mb-4">
                    <div class="col pull-right">
                        <div class="btn-group pull-right" role="group">
                            <a href="{{ route('orders.index') }}" class="btn btn-warning pull-right">
                                <i class="fa fa-arrow-left fa-fw"></i> Back
                            </a>
                            <a href="{{ route('orders.edit', ['order'=>$order->id]) }}" class="btn btn-primary pull-right">
                                <i class="fa fa-edit fa-fw"></i> Manage
                            </a>
                            <a href="{{ url('orders/'.$order->id.'/delete') }}" class="btn btn-danger pull-right" onclick="return confirm('Are you sure? This action will permanently delete this order')">
                                <i class="fa fa-trash fa-fw"></i> Delete
                            </a>
                        </div>
                        <h3>View @yield('title')</h3>
                    </div>
                </div>

                <div class="row">

                    <div class="col-12">
                        @include('common.boxes')
                    </div>

                    {{--Product Info--}}
                    <div class="col-4">
                        <h4>Product Details</h4>
                        <div class="list-group">
                            <div class="list-group-item list-group-item-action flex-column align-items-start">
                                <small class="text-muted">Item</small>
                                <div class="d-flex w-100 justify-content-between">
                                    <h4 class="mb-1">{{ $order->ad->name }}</h4>
                                </div>
                            </div>
                            <div class="list-group-item list-group-item-action flex-column align-items-start">
                                <small class="text-muted">Price</small>
                                <div class="d-flex w-100 justify-content-between">
                                    <h4 class="mb-1">Ksh {{ number_format($order->ad->price) }}</h4>
                                </div>
                            </div>
                            <div class="list-group-item list-group-item-action flex-column align-items-start">
                                <small class="text-muted">Location</small>
                                <div class="d-flex w-100 justify-content-between">
                                    <h4 class="mb-1">{{ @$order->ad->location['display_name'] }}</h4>
                                </div>
                            </div>
                            <div class="list-group-item list-group-item-action flex-column align-items-start">
                                <small class="text-muted">Posted under</small>
                                <div class="d-flex w-100 justify-content-between">
                                    <h4 class="mb-1">{{ @$order->ad->category }}</h4>
                                </div>
                            </div>
                        </div>
                    </div>

                    {{--Publisher info--}}
                    <div class="col-4">
                        <h4>Seller Details</h4>
                        <div class="list-group">
                            <div class="list-group-item list-group-item-action flex-column align-items-start">
                                <small class="text-muted">Publisher Name</small>
                                <div class="d-flex w-100 justify-content-between">
                                    <h4 class="mb-1">{{ $order->ad->publisher->name }}</h4>
                                </div>
                            </div>
                            <div class="list-group-item list-group-item-action flex-column align-items-start">
                                <small class="text-muted">Publisher Email</small>
                                <div class="d-flex w-100 justify-content-between">
                                    <h4 class="mb-1">
                                        <a href="#">{{ $order->ad->email }}</a>
                                    </h4>
                                </div>
                            </div>
                            <div class="list-group-item list-group-item-action flex-column align-items-start">
                                <small class="text-muted">Publisher Telephone</small>
                                <div class="d-flex w-100 justify-content-between">
                                    <h4 class="mb-1">{{ $order->ad->telephone }}</h4>
                                </div>
                            </div>
                            <div class="list-group-item list-group-item-action flex-column align-items-start">
                                <small class="text-muted">Publisher Gender</small>
                                <div class="d-flex w-100 justify-content-between">
                                    <h4 class="mb-1">{{ config('settings.gender')[$order->ad->publisher->gender] }}</h4>
                                </div>
                            </div>
                        </div>
                    </div>

                    {{--Images--}}
                    <div class="col-4">
                        <h4>Product Images</h4>
                        <div class="slider">
                            @foreach($order->ad->pictures as $picture)
                                <div>
                                    <img class="d-block w-100" src="{{ $picture }}">
                                </div>
                            @endforeach
                        </div>
                    </div>
                </div>

                <div class="row mt-4">

                    {{--Order instructions--}}
                    <div class="col-6">
                        <div class="bgc-white bd bdrs-3 p-20 mB-20">
                            <h4 class="c-grey-900 mB-20">Order Instructions</h4>
                            <p>{{ $order->instructions}}</p>
                        </div>
                    </div>

                    {{--Customer Location--}}
                    @if($order->ad->category == 'CATERING')
                        <div class="col-6">
                            <div class="bgc-white bd bdrs-3 p-20 mB-20">
                                <h4 class="c-grey-900 mB-20">Catering Options</h4>
                                <div class="list-group">
                                    <div class="list-group-item list-group-item-action flex-column align-items-start">
                                        <small class="text-muted">Event Type</small>
                                        <div class="d-flex w-100 justify-content-between">
                                            <h4 class="mb-1">{{ config('settings.catering.event_types')[$order->extra_data['type']] }}</h4>
                                        </div>
                                    </div>
                                    <div class="list-group-item list-group-item-action flex-column align-items-start">
                                        <small class="text-muted">Event Venue</small>
                                        <div class="d-flex w-100 justify-content-between">
                                            <h4 class="mb-1">{{ config('settings.catering.venues')[$order->extra_data['venue']] }}</h4>
                                        </div>
                                    </div>
                                    <div class="list-group-item list-group-item-action flex-column align-items-start">
                                        <small class="text-muted">Location</small>
                                        <div class="d-flex w-100 justify-content-between">
                                            <h4 class="mb-1">{{ @$order->extra_data['location']['display_name'] }}</h4>
                                        </div>
                                    </div>
                                    <div class="list-group-item list-group-item-action flex-column align-items-start">
                                        <small class="text-muted">Number of attendees</small>
                                        <div class="d-flex w-100 justify-content-between">
                                            <h4 class="mb-1">{{ $order->extra_data['attendees'] }} people might attend</h4>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    @else
                        <div class="col-6">
                            <div class="bgc-white bd bdrs-3 p-20 mB-20">
                                <h4 class="c-grey-900 mB-20">Customer Location</h4>
                                <p>{{ $order->description }}</p>
                            </div>
                        </div>
                    @endif

                </div>

                {{--Activity log--}}
                <div class="row mt-4">
                    <div class="col-12">
                        <button type="button" class="btn btn-primary pull-right" data-toggle="modal" data-target="#exampleModal">
                            <i class="fa fa-plus-circle fa-fw"></i> Add a note
                        </button>
                        <h4>
                            <i class="fa fa-comments fa-fw"></i> Staff Notes - {{ $order->logs->count() }}
                        </h4>
                        <div class="list-group mt-3">
                            @foreach($order->logs as $log)
                                <div class="list-group-item list-group-item-action flex-column align-items-start">
                                    <p class="mb-1">
                                        {{ $log->message }}
                                    </p>
                                    <div class="d-flex w-100 justify-content-between">
                                        <small class="text-muted">
                                            <i class="fa fa-user-circle fa-fw"></i> Written by {{ $log->_publisher->name }}
                                        </small>
                                        <small class="text-muted pull-right">
                                            <i class="fa fa-clock-o fa-fw"></i> {{ $log->created_at->diffForHumans() }}
                                        </small>
                                    </div>
                                </div>
                            @endforeach
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </main>

    <!-- Add staff note -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Add a note on this order</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    {!! Form::open(['url'=>'orders/'.$order->id.'/note']) !!}
                    <div class="form-group">
                        <label>Message</label>
                        {!! Form::textarea('note', null, ['placeholder'=>'Type your message...', 'class'=>'form-control']) !!}
                    </div>
                    {!! Form::close() !!}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" onclick="$('form').submit()">Save changes</button>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('header-scripts')
    <link rel="stylesheet" type="text/css" href="{{ asset('slick-1.8.1/slick/slick.css', env('FORCE_SSL')) }}"/>
    <link rel="stylesheet" type="text/css" href="{{ asset('slick-1.8.1/slick/slick-theme.css', env('FORCE_SSL')) }}"/>
@endpush

@push('footer-scripts')
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
    <script>
        $(function () {
            $('.slider').slick({
                dots: true,
                autoplay: true
            });
        })
    </script>
@endpush